name: local_notifaiction
description: You can make a note and you will be reminded according to the time specified

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
  


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^9.1.4
  flutter_native_timezone: ^1.0.10
  get_storage: ^2.0.3 
  get: ^4.3.8
  easy_localization: ^3.0.0
  
  intl:
  google_fonts:
  date_picker_timeline:
  sqflite:
  flutter_staggered_animations:
  rxdart: ^0.26.0
  infinite_scroll_pagination: ^3.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0
  
dependency_overrides:
  # fix `packageRoot`compile error for iOS, because `path_provider` is using an old version of `platform`
  platform: ^3.1.0 

flutter:


  uses-material-design: true

  assets:
     - images/
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
